# Generated by Django 5.1.3 on 2024-12-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(default='Ford', max_length=20)),
                ('modelo', models.CharField(max_length=100)),
                ('carroceria', models.CharField(max_length=50)),
                ('motor', models.CharField(max_length=50)),
                ('categoria', models.CharField(default='Particula', help_text='Puede ser Particular, Transporte o Carga', max_length=20)),
                ('precio', models.IntegerField()),
                ('fecha_de_creacion', models.DateField(blank=True, null=True)),
                ('fecha_de_modificacion', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
