# Generated by Django 4.0.5 on 2024-12-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='categoria',
            field=models.CharField(choices=[('particular', 'particular'), ('transporte', 'transporte'), ('carga', 'carga')], default='Particula', help_text='Puede ser Particular, Transporte o Carga', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_de_creacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_de_modificacion',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(choices=[('Fiar', 'Fiat'), ('Chevrolet', 'Chevrolet'), ('Ford', 'Ford'), ('Toyota', 'Toyota')], default='Ford', max_length=20),
        ),
    ]
