# Generated by Django 4.0.5 on 2024-12-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_alter_vehiculo_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': [('visualizador_catalogo', 'Puede ver el catalogo de vahiculos')]},
        ),
    ]
