# Generated by Django 4.0.5 on 2024-12-09 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0003_alter_vehiculo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': [('visualizador_catalogo', 'Puede ver el catalogo de vehiculos')]},
        ),
    ]
